config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users

  root to: "restaurants#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]

  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
  # if have a restaurant, i can do restaurant.reviews

  CATEGORIES = ["Sushi", "Ramen", "Udon", "Tempura", "Curry"]

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  validates :rating, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5}
end

app/models/user.rb
class User < ApplicationRecord
  enum role: { user: 0, owner: 1 }
  has_many :restaurants
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit::Authorization

  after_action :maybe_verify_authorized, unless: :skip_pundit?
  after_action :maybe_verify_policy_scoped, unless: :skip_pundit?

  protected

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :role])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :role])
  end

  private
  def user_not_authorized
    flash[:alert] = "You are not allowed to review your own restaurant."
    redirect_back(fallback_location: root_path)
  end

  def maybe_verify_authorized
    verify_authorized unless action_name == 'index'
  end

  def maybe_verify_policy_scoped
    verify_policy_scoped if action_name == 'index'
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @restaurants = policy_scope(Restaurant).all
    @markers = @restaurants.geocoded.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude
      }
    end

  end

  def show
    authorize @restaurant
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    authorize @restaurant
    if @restaurant.save
      redirect_to restaurant_path(@restaurant), notice: 'Restaurant was successfully created.'
    else
      render :new, status: :unprocessable_entity, notice: 'Restaurant was not created.'
    end
  end

  def edit
    authorize @restaurant
  end

  def update
    authorize @restaurant
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant), notice: 'Restaurant was successfully updated.'
    else
      render :edit, status: :unprocessable_entity, alert: 'Restaurant was not updated.'
    end
  end

  def destroy
    authorize @restaurant
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category, :photo)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
    @review.restaurant = @restaurant
    authorize @review
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = current_user.reviews.new(review_params)
    @review.restaurant = @restaurant
    authorize @review
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

    @restaurants = @user.restaurants
    @reviews = @user.reviews
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css", media: "all" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>

  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for (restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::CATEGORIES, prompt: "Select a category" %>
  <%= f.input :photo, as: :file, label: "Upload a photo" %>
  <%= f.submit 'Submit', class: 'btn btn-success mt-2' %>
<% end %>

app/views/restaurants/_review-card.erb
<% @restaurant.reviews.each do |review| %>
<div class="card shadow-sm border-1 rounded-lg">
  <div class="card-body">
    <div class="d-flex align-items-center mb-3">
      <div class="rounded-circle bg-danger text-white d-flex align-items-center justify-content-center" style="width: 48px; height: 48px; font-weight: 600; font-size: 1.25rem;">
        <%= review.user.first_name&.first&.upcase %><%= review.user.last_name&.first&.upcase %>
      </div>
      <div class="ms-3">
        <div class="fw-medium text-dark"><%= review.user.first_name %> <%= review.user.last_name %></div>
        <div class="text-muted small">Content Creator</div>
      </div>
    </div>

    <div class="text-danger mb-2 fs-5">
      <%= "⭐️" * review.rating %>
    </div>

    <p class="text-secondary">
      <%= review.content %>
    </p>


  </div>
</div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit</h1>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<div class="d-flex" style="height: 100vh;">
  <div class="d-flex col-7">

    <div class="col-2">
      <!-- grid-->
    </div>

  <div class="col-10">
    <h2 class="py-4">Restaurants in Shibuya</h1>
    <% @restaurants.each do |restaurant| %>
        <%= link_to restaurant_path(restaurant), class: "text-decoration-none text-dark" do %>
          <div class="card-product my-1">
            <% if restaurant.photo.attached? %>
              <%= cl_image_tag restaurant.photo.key, height: 400, width: 400, crop: :fill %>
            <% else %>
              <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
            <% end %>
          <div class="card-product-infos">
            <h2><%= restaurant.name %></h2>
            <p><%= restaurant.reviews.average(:rating).to_f.round(1)%>⭐️ (<%= restaurant.reviews.count %> reviews)</p>
            <p><%= restaurant.address %></p>
            <p><%= restaurant.category %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

</div>
  <div class="col-5">
    <div class="map-container">
        <div class="map-view"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<h1>Form</h1>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "RestaurantsBackground.png" %>);">
  <div class="container">
    <h1>Welcome to <%= @restaurant.name %></h1>
    <p><%= @restaurant.reviews.average(:rating).to_f.round(1)%>⭐️ (<%= @restaurant.reviews.count %> reviews)</p>
    <p><%= @restaurant.category %></p>
  </div>
</div>

<div class="container d-flex pt-5">
  <div class="col-8 pe-5">
    <div class="mb-4 border-bottom pb-4">


    <%= link_to "☆ Write a review", new_restaurant_review_path(@restaurant), class: "btn btn-success" %>

    </div>

    <div class="border-bottom" style="height: 320px">
      <div class="map-container" style="height: 200px; width: 350px">
        <p><strong>Location</strong></p>
        <div class="map-view"
          data-controller="map"
          data-map-markers-value='<%= [{ lat: @restaurant.latitude, lng: @restaurant.longitude }].to_json %>'
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
        <p><%= @restaurant.address %></p>
      </div>
    </div>


    <div class="mt-5"><%= render "review-card" %></div>

  </div>

  <div class="col-4">
    <div class="card" style="max-width: 300px">
      <div><p class="border-bottom text-decoration-none text-dark p-3"><i class="fa-solid fa-user-secret"></i> <%= @restaurant.user.first_name %> <%= @restaurant.user.last_name %></p></div>
      <div><p class="px-3 pb-3 border-bottom"><i class="fa-solid fa-phone-volume"></i> <%= @restaurant.phone_number %></p></div>
      <div>
      <p class="px-3"><i class="fa-solid fa-map-location-dot"></i> Get Directions</p>
      <p class="px-3"><%= @restaurant.address %></p></div>
    </div>
  </div>
</div>

<p>
  <% if policy(@restaurant).edit? %>
    <%= link_to "Edit Restaurant", edit_restaurant_path, class: "btn btn-primary" %>
  <% end %>
</p>

<% if policy(@restaurant).destroy? %>
  <%= link_to "Delete Restaurant", restaurant_path(@restaurant), class: "btn btn-danger",
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
<% end %>

app/views/reviews/_form.html.erb
<h1>New review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating, input_html: {min: 0, max: 5} %>
  <%= f.input :content %>
  <%= f.submit 'Submit', class: 'btn btn-success mt-2' %>
<% end %>

app/views/reviews/new.html.erb
<%= render "form", restaurant: @restaurant, review: @review %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border-bottom" style="height: 100px;">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", restaurants_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
            <%= link_to "Home", restaurants_path, class: "btn btn-light border" %>
            <%= link_to "Login", new_user_session_path, class: "btn btn-light border mx-4" %>
            <%= link_to "Sign up", new_user_registration_path, class: "rounded-3 btn btn-danger" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Welcome <%= @user.first_name %> <%= @user.last_name %></h1>

<p>Your email: <%= @user.email %></p>

<p>Role: <%= @user.role %></p>

<% if @restaurants.any? %>
  <h2 class="py-4">Restaurants owned by <%= @user.first_name %>:</h2>
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-md-6 col-lg-4 mb-4">
        <%= link_to restaurant_path(restaurant), class: "text-decoration-none text-dark" do %>
          <div class="card-product my-1">
            <% if restaurant.photo.attached? %>
              <%= cl_image_tag restaurant.photo.key, height: 400, width: 400, crop: :fill %>
            <% else %>
              <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
            <% end %>
            <div class="card-product-infos">
              <h2><%= restaurant.name %></h2>
              <p><%= restaurant.reviews.average(:rating).to_f.round(1) %>⭐️ (<%= restaurant.reviews.count %> reviews)</p>
              <p><%= restaurant.address %></p>
              <p><%= restaurant.category %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

<% if @user.owner? %>
  <%= link_to "Add New Restaurant", new_restaurant_path, class: "btn btn-success mt-4" %>
<% end %>